### PR TITLE
Adding the get_distinct_id function from the docs.

### PR DESCRIPTION
**Pull request by kartikluke**
https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.get_distinct_id

### CODE REVIEW

**Comment by kartikluke** [comment]
Clearly this is isn't the correct way to get the current distinct_id value. It returns an #<Mengpaneel::CallProxy> object. I'm assuming the object waits on a call to mixpanel. Could you help me out @DouweM

**Comment by kartikluke** [comment]
What I'm trying to do is track an event to another user. In my case an Admin approves a user and I want to then set a property on that user. But the way we're calling functions we have `distinct_id` based on identify. So I thought I'd store the current `distinct_id` and then identify as the user using their distinct id. Track the property and then identify back as an admin. Is there a better way of tracking an event or registering a property to another user.

**Comment by kartikluke** [comment]
Actually I've decided to do it through `mixpanel-ruby`. Doesn't make sense to edit Mengpaneel to make this possible. This gem is pretty awesome btw.

**Comment by DouweM** [comment]
@kartikluke Glad you figured it out, and thanks for the nice words :)

**Pull request closed without merging**
